### ISSUE TITLE
Auto-select most appropriate axes for plots

### ISSUE THREAD

**Issue by naught101** [titusjan/argos#9]
It's quite common in netcdf files to have variables that are one or two dimensions, but are indexed over three or four dimensions. When plotting these variables, it often happens that Argos just selects the first dimension to plot over, which may only have one value, and so no plot is produced. You then need to manually select the mapping to each axis.

e.g. I have a single-site met file, that has rainfall indexed by (x, y, time), but it only has information in the time dimension.

It would be good if Argos aotomatically detected non-informative dimensions, and preferentially selected other dimensions by default for plotting. This would make the workflow slightly faster and less annoying for users, and would be significantly less confusing for new users (it took me a while to work out why it wasn't plotting...).

**Comment by titusjan** [comment]
The current situation is that, If there are more dimensions in the dataset than the inspector can show, Argos selects the last couple of dimensions in the combobox(es). This was chosen because the [NetCDF-CF conventions](http://cfconventions.org/) have the preferred dimension order of T, Z, Y, X. 

In your example above, assuming you show a 1D line plot, Argos would put the `time` dimension in the X-axis combobox, so I this would be rendered fine.

In any case, your point still stands. There will be situations where Argos puts a dimension of length 1 in a combobox. This might be confusing. I therefore implemented your suggestion. You can try it out in the `devel` branch.

**Comment by naught101** [comment]
That's much better, thanks!
